# Generated by Django 3.0.8 on 2020-08-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0003_tbl_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_reg',
            name='typ',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
