# Generated by Django 3.0.8 on 2020-08-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0004_tbl_reg_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_log',
            name='typ',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
