# Generated by Django 3.0.8 on 2020-08-06 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0005_tbl_log_typ'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_log',
        ),
    ]
