# Generated by Django 3.1 on 2020-09-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0008_auto_20200909_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_reg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='file'),
        ),
    ]
