# Generated by Django 3.1 on 2020-09-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0009_tbl_reg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_log',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='file'),
        ),
    ]
