# Generated by Django 3.1 on 2020-09-16 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0010_tbl_log_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_log',
            name='image',
        ),
    ]
