# Generated by Django 3.1 on 2020-08-26 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_tbl_umsg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_upro',
        ),
    ]
