# Generated by Django 3.1 on 2020-08-27 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_delete_tbl_upro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_umsg',
        ),
    ]
