# Generated by Django 3.1 on 2020-08-27 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makerapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_mpro',
        ),
    ]
